instrumentation:
  include-all-sources: true
  verbose: true
  root: src/client
  excludes: ["*.test.js", "*.e2e.js", "__setup__.js", "fixtures/*", "index.js"]
reporting:
  dir: "coverage/client-unit"